# =====================================================
# Config files
# =====================================================
configfile: "config/config.yaml"

#======================================================
# Samples
#======================================================
dir1 = ['1hour_coriolis_barcode' + n for n in ['03', '04', '05', '08', '09', '10', '13', '14', '15']]
dir23 = ['2_and_3hours_coriolis_barcode' + n for n in ['01', '20', '21', '22', '23', '24']]
ASSEMBLY_SAMPLES = dir1 + dir23 
#======================================================
#Pipeline
#======================================================
rule all:
	input:
		expand("results/current/gtdbtk/{s}.bac120.summary.tsv", s=ASSEMBLY_SAMPLES),
		#expand("results/current/vamb/{s}/bins/clusters.tsv", s=ASSEMBLY_SAMPLES),
		#expand("results/current/maxbin2/{s}/{s}.summary", s=ASSEMBLY_SAMPLES),
                #expand("results/current/metabat2/{s}/{s}", s=ASSEMBLY_SAMPLES),	
		#expand("results/current/das_tool/{s}/{s}_DASTool_summary.txt", s=ASSEMBLY_SAMPLES),
	#	expand("results/current/coverm/{s}_summary.txt", s=ASSEMBLY_SAMPLES),
	#	expand("results/current/gtdbtk/{s}/classify/{s}_bac120_classify_itol.tree", s=ASSEMBLY_SAMPLES),

#======================================================
#Rules
#======================================================
include: "rules/bioawk.smk"
include: "rules/metabat2.smk"
include: "rules/vamb_workflow.smk"
include: "rules/maxbin2.smk"
include: "rules/filter_vamb_bins.smk"
include: "rules/das_tools.smk"
include: "rules/coverm.smk"
include: "rules/gtdbtk.smk"
