# ======================================================
# Config files
# ======================================================
configfile: "config/config.yaml"

#======================================================
# Rules
#======================================================

ALL_SAMPLES = ["shotgun_new", "shotgun_fahad", "BC02_new", "BC03_new", "BC04_new", "BC02_porechop_fahad", "BC03_porechop_fahad", "BC04_porechop_fahad"] 
ASSEMBLY_SAMPLES = ["shotgun_new","shotgun_fahad"]

rule all:
	input:
# QC plots
#		expand("results/current/nanoplot/{s}_NanoPlot-report.html", s=ALL_SAMPLES),
		expand("results/current/vamb/{s}/bins/clusters.tsv", s=ASSEMBLY_SAMPLES),
		expand("results/current/maxbin2/{s}/{s}.summary", s=ASSEMBLY_SAMPLES),
                expand("results/current/metabat2/{s}/{s}", s=ASSEMBLY_SAMPLES)
		
             
# the snakemake files that run the different parts of the pipeline
include: "rules/guppy.smk"
include: "rules/guppy_barcoder.smk"
include: "rules/porechop.smk"
include: "rules/nanoplot.smk"
include: "rules/nanofilt.smk"
include: "rules/flye.smk"
include: "rules/minimap2_raconX.smk"
include: "rules/medaka_1_align.smk"
include: "rules/medaka_2_consensus.smk"
include: "rules/medaka_3_stitch.smk"
include: "rules/bioawk.smk"
include: "rules/metabat2.smk"
include: "rules/vamb_workflow.smk"
include: "rules/maxbin2.smk"
