# cluster_config.yml - cluster configuration
__default__:
     account: grekova
     partition: cluster
     time: 16:00:00 # time limit for each job in h:m:s
     nodes: 3
     ntasks-per-node: 6 #Request n cores be allocated per node.
